---
- name: Create job templates for playbooks
  hosts: localhost
  gather_facts: false

  vars_files:
    - "{{ lookup('file', (pattern.path | dirname) + '/setup.yml') | from_yaml }}"

  tasks:
    - name: Check if required variables are defined
      assert:
        that:
          - aap_url is defined
          - aap_username is defined
          - aap_password is defined
        fail_msg: "Required variables are missing! aap_url, aap_username, and aap_password must be defined."
        success_msg: "All required variables are defined."

    - name: Create labels
      ansible.controller.label:
        controller_host: "{{ aap_url }}"
        controller_username: "{{ aap_username }}"
        controller_password: "{{ aap_password }}"
        name: "{{ item.name }}"
        organization: "{{ aap_organization | default('Default') }}"
      loop: "{{ controller_labels }}"

    - name: Create projects
      ansible.controller.project:
        controller_host: "{{ aap_url }}"
        controller_username: "{{ aap_username }}"
        controller_password: "{{ aap_password }}"
        name: "{{ item.name }}"
        description: "{{ item.description }}"
        organization: "{{ aap_organization | default('Default') }}"
        scm_type: "{{ item.scm_type }}"
        scm_url: "{{ item.scm_url }}"
        state: "present"
      loop: "{{ controller_projects }}"

    - name: Create job templates
      ansible.controller.job_template:
        controller_host: "{{ aap_url }}"
        controller_username: "{{ aap_username }}"
        controller_password: "{{ aap_password }}"
        name: "{{ item.name }}"
        description: "{{ item.description }}"
        organization: "{{ aap_organization | default('Default') }}"
        project: "{{ item.project }}"
        playbook: "{{ item.playbook }}"
        job_type: "run"
        labels: "{{ item.labels }}"
        survey_enabled: "{{ item.survey_enabled }}"
        survey_spec: "{{ lookup('file', item.survey_file) | from_yaml }}"
        ask_inventory_on_launch: true
        ask_credential_on_launch: true
        ask_labels_on_launch: true
        ask_job_type_on_launch: true
      loop: "{{ controller_templates }}"
