---
- name: Configure AAP using infra.aap_configuration
  hosts: localhost
  gather_facts: false

  vars:
    controller_labels:
      - name: "demo"
      - name: "rhcop"

    controller_projects:
      - name: "Red Hat Community of Practice / Network Backup & Restore"
        description: "The Ansible Network Backup Validated Content provides a comprehensive solution for managing network backups and restores across supported network platforms. This validated content offers two key functionalities: backup and restore, each designed to be platform-agnostic and user-friendly."
        scm_type: "git"
        scm_url: "https://github.com/redhat-cop/network.backup"
        scm_update_on_launch: true
        id: network.backup

      - name: "Red Hat Community of Practice / AWS Operations"
        description: "This collection is curated to provide users with a robust set of roles, playbooks, and rulebooks that simplify and streamline various AWS operations."
        scm_type: "git"
        scm_url: "https://github.com/redhat-cop/cloud.aws_ops"
        scm_update_on_launch: true
        id: cloud.aws_ops

    controller_templates:
      - name: "Red Hat Community of Practice / Network Backup"
        description: "This job template executes the run_network_backup.yaml playbook to automate the backup of network configurations. It captures essential network settings and securely stores them, ensuring that they can be restored if needed. The job template can be scheduled for regular backups to maintain up-to-date network configurations."
        project: "Red Hat Community of Practice / Network Backup & Restore"
        playbook: "extensions/patterns/backup/playbooks/run_network_backup.yaml"
        labels: "network,backup,rhcop"
        survey_enabled: true
        survey_file: "extensions/patterns/backup/template_surveys/backup.yaml"
        id: network.backup

      - name: "Red Hat Community of Practice / Network Restore"
        description: "This job template runs the run_network_restore.yaml playbook to restore previously backed-up network configurations. It ensures that network settings are accurately re-applied, enabling recovery from failures or replication of network environments. The job template can be triggered to restore network configurations as needed."
        project: "Red Hat Community of Practice / Network Backup & Restore"
        playbook: "extensions/patterns/restore/playbooks/run_network_restore.yaml"
        labels: "network,backup,rhcop"
        survey_enabled: true
        survey_file: "extensions/patterns/restore/template_surveys/restore.yaml"
        id: network.backup

      - name: "Red Hat Community of Practice / Create AWS EC2 Instance"
        description: "This job template runs the create_ec2_instance.yml playbook to automate the provisioning of EC2 instances on AWS. It simplifies the process of creating and configuring EC2 instances by capturing necessary parameters through a survey, ensuring a consistent and repeatable instance creation process."
        project: "Red Hat Community of Practice / AWS Operations"
        playbook: "extensions/patterns/configure_ec2/playbooks/create_ec2_instance.yml"
        labels: "aws,ec2,rhcop"
        survey_enabled: true
        survey_file: "extensions/patterns/configure_ec2/template_surveys/create_ec2_instance.yml"
        id: cloud.aws_ops

      - name: "Red Hat Community of Practice / Terminate AWS EC2 Instance"
        description: "This job template runs the terminate_ec2_instance.yml playbook to automate the safe termination of EC2 instances on AWS. It ensures that instances are properly terminated, releasing associated resources, and preventing unnecessary costs. The job template can be executed to clean up EC2 instances as needed."
        project: "Red Hat Community of Practice / AWS Operations"
        playbook: "extensions/patterns/configure_ec2/playbooks/terminate_ec2_instance.yml"
        labels: "aws,ec2,rhcop"
        survey_enabled: true
        survey_file: "extensions/patterns/configure_ec2/template_surveys/terminate_ec2_instance.yml"
        id: cloud.aws_ops

  tasks:
    - name: Configure AAP
      infra.aap_configuration:
        controller_host: "{{ aap_url }}"
        controller_username: "{{ aap_username }}"
        controller_password: "{{ aap_password }}"
        labels: "{{ controller_labels }}"
        projects: "{{ controller_projects }}"
        job_templates: "{{ controller_templates }}"
        validate_certs: false
