---
- name: Create job templates for playbooks
  hosts: localhost
  gather_facts: false

  vars:
    labels:
      - name: "aws"
      - name: "ec2"
      - name: "cloud.aws_ops"

    projects:
      - name: "JTalton / AWS Operations"
        description: "This collection is curated to provide users with a robust set of roles, playbooks, and rulebooks that simplify and streamline various AWS operations."
        scm_type: "git"
        scm_url: "https://github.com/redhat-cop/cloud.aws_ops"
        scm_update_on_launch: true

    templates:
      - name: "JTalton / Create AWS EC2 Instance"
        description: "This job template creates an AWS EC2 instance and associated networking resources."
        project: "JTalton / AWS Operations"
        playbook: "extensions/patterns/configure_ec2/playbooks/create_ec2_instance.yml"
        labels: "aws,ec2,cloud.aws_ops"
        survey_enabled: true
        survey_file: "extensions/patterns/configure_ec2/template_surveys/create_ec2_instance.yml"

  tasks:
    - name: Check if required variables are defined
      assert:
        that:
          - aap_url is defined
          - aap_username is defined
          - aap_password is defined
        fail_msg: "Required variables are missing! aap_url, aap_username, and aap_password must be defined."
        success_msg: "All required variables are defined."

    - name: Create labels
      ansible.controller.label:
        controller_host: "{{ aap_url }}"
        controller_username: "{{ aap_username }}"
        controller_password: "{{ aap_password }}"
        name: "{{ item.name }}"
        organization: "{{ aap_organization | default('Default') }}"
      loop: "{{ labels }}"

    - name: Create projects
      ansible.controller.project:
        controller_host: "{{ aap_url }}"
        controller_username: "{{ aap_username }}"
        controller_password: "{{ aap_password }}"
        name: "{{ item.name }}"
        description: "{{ item.description }}"
        organization: "{{ aap_organization | default('Default') }}"
        scm_type: "{{ item.scm_type }}"
        scm_url: "{{ item.scm_url }}"
        state: "present"
      loop: "{{ projects }}"

    - name: Create job templates
      ansible.controller.job_template:
        controller_host: "{{ aap_url }}"
        controller_username: "{{ aap_username }}"
        controller_password: "{{ aap_password }}"
        name: "{{ item.name }}"
        description: "{{ item.description }}"
        organization: "{{ aap_organization | default('Default') }}"
        project: "{{ item.project }}"
        playbook: "{{ item.playbook }}"
        job_type: "run"
        labels: "{{ item.labels }}"
        survey_enabled: "{{ item.survey_enabled }}"
        survey_spec: "{{ lookup('file', item.survey_file) | from_yaml }}"
        ask_inventory_on_launch: true
        ask_credential_on_launch: true
        ask_labels_on_launch: true
        ask_job_type_on_launch: true
      loop: "{{ templates }}"
