---
- name: List available collections in EE
  hosts: localhost
  gather_facts: false
  tasks:
    - name: List installed collections
      command: ansible-galaxy collection list
      register: collections_output
      changed_when: false

    - name: Show installed collections
      debug:
        msg: "{{ collections_output.stdout }}"
