---
- name: Create job templates for playbooks
  hosts: localhost
  gather_facts: false

  vars:
    projects:
      - name: "Project 1"
        description: "Description for Project 1"
        organization: "Default"
        scm_type: "git"
        scm_url: "http://git.example.com/project1.git"

    templates:
      - name: "Template 1"
        description: "Description for Template 1"
        organization: "Default"
        inventory: "Inventory 1"
        project: "Project 1"
        playbook: "playbook1.yml"
        credential: "Credential 1"

  tasks:
    - name: Create projects
      ansible.controller.project:
        controller_host: "{{ aap_url }}"
        controller_username: "{{ aap_username }}"
        controller_password: "{{ aap_password }}"
        name: "{{ item.name }}"
        description: "{{ item.description }}"
        organization: "{{ item.organization }}"
        scm_type: "{{ item.scm_type }}"
        scm_url: "{{ item.scm_url }}"
        state: "present"
      loop: "{{ projects }}"

    - name: Create job templates
      ansible.controller.job_template:
        controller_host: "{{ aap_url }}"
        controller_username: "{{ aap_username }}"
        controller_password: "{{ aap_password }}"
        headers:
          Authorization: "Bearer {{ aap_token }}"
        name: "{{ item.name }}"
        description: "{{ item.description }}"
        organization: "{{ item.organization }}"
        inventory: "{{ item.inventory }}"
        project: "{{ item.project }}"
        playbook: "{{ item.playbook }}"
        credential: "{{ item.credential }}"
        job_type: "run"
        state: "present"
      loop: "{{ templates }}"
