---
- name: Create job templates for playbooks
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create job templates
      ansible.tower.tower_job_template:
        name: "{{ item.name }}"
        description: "{{ item.description }}"
        organization: "{{ item.organization }}"
        inventory: "{{ item.inventory }}"
        project: "{{ item.project }}"
        playbook: "{{ item.playbook }}"
        credential: "{{ item.credential }}"
        job_type: "run"
        state: "present"
      loop: "{{ templates }}"
