---
- name: Create job templates for playbooks
  hosts: localhost
  gather_facts: false

  vars:
    projects:
      - name: "AWS Validate Content"
        description: "This collection is curated to provide users with a robust set of roles, playbooks, and rulebooks that simplify and streamline various AWS operations."
        organization: "Default"
        scm_type: "git"
        scm_url: "https://github.com/redhat-cop/cloud.aws_ops"

    templates:
      - name: "AWS Create EC2 Instance"
        description: "Description for Template 1"
        organization: "Default"
        project: "AWS Validate Conten"
        playbook: "extensions/patternf/configure_ec2/playbooks/create_ec2_instance.yml"
        ask_inventory_on_launch: true
        ask_credential_on_launch: true

  tasks:
    - name: Create projects
      ansible.controller.project:
        controller_host: "{{ aap_url }}"
        controller_username: "{{ aap_username }}"
        controller_password: "{{ aap_password }}"
        name: "{{ item.name }}"
        description: "{{ item.description }}"
        organization: "{{ item.organization }}"
        scm_type: "{{ item.scm_type }}"
        scm_url: "{{ item.scm_url }}"
        state: "present"
      loop: "{{ projects }}"

    - name: Create job templates
      ansible.controller.job_template:
        controller_host: "{{ aap_url }}"
        controller_username: "{{ aap_username }}"
        controller_password: "{{ aap_password }}"
        headers:
          Authorization: "Bearer {{ aap_token }}"
        name: "{{ item.name }}"
        description: "{{ item.description }}"
        organization: "{{ item.organization }}"
        inventory: "{{ item.inventory }}"
        project: "{{ item.project }}"
        playbook: "{{ item.playbook }}"
        credential: "{{ item.credential }}"
        job_type: "run"
        state: "present"
      loop: "{{ templates }}"
