---
- name: Create job templates for playbooks
  hosts: localhost
  gather_facts: false

  vars:
    labels:
      - name: "aws"
      - name: "ec2"
      - name: "instance"

    projects:
      - name: "AWS Validate Content"
        description: "This collection is curated to provide users with a robust set of roles, playbooks, and rulebooks that simplify and streamline various AWS operations."
        organization: "Default"
        scm_type: "git"
        scm_url: "https://github.com/redhat-cop/cloud.aws_ops"
        scm_update_on_launch: true

    templates:
      - name: "AWS Create EC2 Instance"
        description: "Description for Template 1"
        organization: "Default"
        project: "AWS Validate Content"
        playbook: "extensions/patterns/configure_ec2/playbooks/create_ec2_instance.yml"
        labels: "aws,ec2,instance"
        survey_enabled: true
        survey_spec:
          name: "AWS Create EC2 Instance"
          description: "Description for Survey 1"
          spec:
            - question_name: "instance_type"
              question_description: "Select the instance type"
              question_type: "multiplechoice"
              type: "multiplechoice"
              required: true
              min: 1
              max: 1
              choices:
                - name: "t2.micro"
                  description: "t2.micro"
                - name: "t2.small"
                  description: "t2.small"
                - name: "t2.medium"
                  description: "t2.medium"
                - name: "t2.large"
                  description: "t2.large"
            - question_name: "instance_count"
              question_description: "Enter the number of instances"
              question_type: "integer"
              type: "integer"
              required: true
              min: 1
              max: 10
            - question_name: "instance_name"
              question_description: "Enter the instance name"
              question_type: "text"
              type: "text"
              required: true
              min: 1
              max: 50

  tasks:
    - name: Check if required variables are defined
      assert:
        that:
          - aap_url is defined
          - aap_username is defined
          - aap_password is defined
        fail_msg: "Required variables are missing! aap_url, aap_username, and aap_password must be defined."
        success_msg: "All required variables are defined."

    - name: Create labels
      ansible.controller.label:
        controller_host: "{{ aap_url }}"
        controller_username: "{{ aap_username }}"
        controller_password: "{{ aap_password }}"
        name: "{{ item.name }}"
        organization: "Default"
      loop: "{{ labels }}"

    - name: Create projects
      ansible.controller.project:
        controller_host: "{{ aap_url }}"
        controller_username: "{{ aap_username }}"
        controller_password: "{{ aap_password }}"
        name: "{{ item.name }}"
        description: "{{ item.description }}"
        organization: "{{ item.organization }}"
        scm_type: "{{ item.scm_type }}"
        scm_url: "{{ item.scm_url }}"
        state: "present"
      loop: "{{ projects }}"

    - name: Create job templates
      ansible.controller.job_template:
        controller_host: "{{ aap_url }}"
        controller_username: "{{ aap_username }}"
        controller_password: "{{ aap_password }}"
        name: "{{ item.name }}"
        description: "{{ item.description }}"
        organization: "{{ item.organization }}"
        project: "{{ item.project }}"
        playbook: "{{ item.playbook }}"
        job_type: "run"
        labels: "{{ item.labels }}"
        survey_enabled: "{{ item.survey_enabled }}"
        survey_spec: "{{ item.survey_spec }}"
        ask_inventory_on_launch: true
        ask_credential_on_launch: true
        ask_labels_on_launch: true
        ask_job_type_on_launch: true
      loop: "{{ templates }}"
